# Generated by Django 3.2.17 on 2023-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='aoygen_bed_availble',
            new_name='oxygen_bed_availble',
        ),
    ]
