# Generated by Django 3.2.17 on 2023-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230826_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='available',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='total',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
